Toughen: Add `source` helper that alerts if dependency unlocatable

diff --git a/bin/infuse-configlns b/bin/infuse-configlns
--- a/bin/infuse-configlns
+++ b/bin/infuse-configlns
@@ -13,7 +13,28 @@ MREDIT_CONFIGS="${MREDIT_CONFIGS:-${HOME}/.mrconfiglns}"
 # +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #
 
 source_deps () {
-  . "$(dirname "$(realpath "$0")")/../lib/link_deep.sh"
+  # Load: link_deep, and remove_symlink_hierarchy_safe.
+  source_dep "lib/link_deep.sh"
+}
+
+source_dep () {
+  local dep_path="$1"
+
+  local project_root
+  project_root="$(dirname "$(realpath "$0")")/.."
+
+  local dep_path="${project_root}/${dep_path}"
+
+  if [ ! -f "${dep_path}" ]; then
+    >&2 echo "ERROR: Could not identify infuse-configlns dependency path."
+    >&2 echo "- Hint: Did you *copy* bin/infuse-configlns somewhere on PATH?"
+    >&2 echo "  - Please use a symlink instead."
+    >&2 echo "- Our incorrect dependency path guess: “${dep_path}”"
+
+    exit 1
+  fi
+
+  . "${dep_path}"
 }
 
 # +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #
